config/routes.rb
Rails.application.routes.draw do
  get 'menus/new'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'static_pages#home'
  get 'static_pages/menu'
  get 'static_pages/contact'
  get 'static_pages/show'
  resources :menus # devise_for :users
  resources :entries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
has_one_attached :image
validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "画像フォーマットは,jpeg, gif, pngにしてください" },
                      size:       { less_than: 5.megabytes,
                                      message: "ファイル容量は5MB以下としてください" }

end

app/models/menu.rb
class Menu < ApplicationRecord
has_one_attached :image
validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "画像フォーマットは,jpeg, gif, pngにしてください" },
                      size:       { less_than: 5.megabytes,
                                      message: "ファイル容量は5MB以下としてください" }

end

app/models/new.rb
class New < ApplicationRecord
has_one_attached :image
validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "画像フォーマットは,jpeg, gif, pngにしてください" },
                      size:       { less_than: 5.megabytes,
                                      message: "ファイル容量は5MB以下としてください" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers:[:twitter]
 # findメソッドを追加
   def self.find_for_oauth(auth)
     user = User.where(uid: auth.uid, provider: auth.provider).first

     unless user
       user = User.create(
         provider: auth.provider,
         uid:      auth.uid,
         username: auth.info.nickname,
         email:    User.dummy_email(auth),
         password: Devise.friendly_token[0, 20]
       )
     end

     user
   end

   private

 # ダミーのアドレスを用意
   def self.dummy_email(auth)
     "#{auth.uid}-#{auth.provider}@example.com"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
    @entry = Entry.new
  end

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.create(entry_params) #strong parameter
    redirect_to '/entries'
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    Entry.find(params[:id]).update(entry_params)
    redirect_to '/entries'
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to '/entries'
  end

  private
    def entry_params
      params.require(:entry).permit(:title, :category, :content, :image)
      #このようにして、imageカラムはテーブルにはないにも関わらずあたかもカラムがあるかのように扱うことで、
      #フォームのfile_fieldで選択された画像をCommentオブジェクトと紐付け。Active Storageの特徴の一つ。
    end

end #of_class

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.create(menu_params) #strong parameter
    @menu.image.attach(params[:menu][:image])
    if @menu.save
      flash[:success]="Menu created!"
      redirect_to '/menus'
    else
      render 'menus/new'
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    Menu.find(params[:id]).update(menu_params)
    redirect_to '/menus'
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    redirect_to '/menus'
  end

private
  def menu_params
    params.require(:menu).permit(:name, :comment, :image)
  end

end#ofClass

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def new
    @new = New.new
  end

  def index
    @news = New.all
  end

  def show
    @new = New.find(params[:id])
  end

  def create
    @new = New.create(new_params) #strong parameter
    redirect_to '/news'
  end

  def edit
    @new = New.find(params[:id])
  end

  def update
    New.find(params[:id]).update(new_params)
    redirect_to '/news'
  end

  def destroy
    @new = New.find(params[:id])
    @new.destroy
    redirect_to '/news'
  end

  private
    def new_params
      params.require(:new).permit(:title, :category, :content, :image)
      #このようにして、imageカラムはテーブルにはないにも関わらずあたかもカラムがあるかのように扱うことで、
      #フォームのfile_fieldで選択された画像をCommentオブジェクトと紐付け。Active Storageの特徴の一つ。
    end

end #of_class

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
# https://techblog.gmo-ap.jp/2019/02/08/rails%E3%81%A7omniauth-twitter%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%A6twitter%E8%AA%8D%E8%A8%BC%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B/
  def twitter
      callback_from :twitter
    end
 
    private

    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def show
    @entries = Entry.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/entries/edit.html.erb
<div id="contact" class="big-bg">
  <div class="wrapper">
    <h2 class="page-title">Edit news</h2>
        <%= form_with(model: @entry, local: true) do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
          <%= f.label :category %>
          <%= f.text_area :category, class: 'form-control' %><BR>
          <%= f.label :content %>
          <%= f.text_area :content, class: 'form-control' %><BR>
          <%= f.label :photo %>
          <%= f.file_field :image %><BR>
          <%= f.submit "Update news", class: "button-create" %>
        <% end %>
        <h3><%= link_to '削除する', entry_path(@entry), method: :delete %></h3>
    </div>
  </div><!-- /.wrapper -->
</div><!-- /#contact -->

app/views/entries/index.html.erb
<h3>News Index Page</h3>
<% @entries.each do |n| %>
  <%= n.id %>
  <%= link_to '編集する', edit_entry_path(n.id) %></br>
  <%= n.updated_at %><br>
  <%= n.title %><br>
  <%= n.category %><br>
  <%= n.content %><br>
  <%= image_tag n.image if n.image.attached? %><br>
<% end %>

app/views/entries/new.html.erb
<div id="contact" class="big-bg">
  <div class="wrapper">
    <h2 class="page-title">Entry news</h2>
        <%= form_with(model: @entry, url: {action: "create"}, local: true) do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
          <%= f.label :category %>
          <%= f.text_area :category, class: 'form-control' %><BR>
          <%= f.label :content %>
          <%= f.text_area :content, class: 'form-control' %><BR>
          <%= f.label :photo %>
          <%= f.file_field :image %><BR>
          <%= f.submit "Create news", class: "button-create" %>
        <% end %>
    </div>
  </div><!-- /.wrapper -->
</div><!-- /#contact -->

app/views/entries/show.html.erb
<h1>This is the show page.</h1>
<h2><%= @entry.title  %></h2>
<h3><%= @entry.category %></h3>
<p><%= @entry.content %></p>
<%= image_tag @entry.image %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="wrapper">
        <p><small>&copy; 2019 Manabox</small></p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="page-header wrapper">
  <h1><%= link_to "WEB CAFE", '/', {class: "page-logo"} %></h1>
    <nav>
        <ul class="main-nav">
            <li><%= link_to "News", '/static_pages/show' %></li>
            <li><%= link_to "Menu", '/menus' %></li>
            <li><%= link_to "Contact", '/static_pages/contact' %></li>
            <% if user_signed_in? %>
            <li><%= link_to 'Edit your profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>

            <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/_menu_form.html.erb
<%= form_with(model: @menu, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :comment %>
  <%= f.text_area :comment, class: 'form-control' %><BR>
  <%= f.label :photo %>
  <%= f.file_field :image %><BR>
  <%= f.submit "update", class: "button-create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Webcafe</title>
    <meta name="description" content="ブレンドコーヒーとヘルシーなオーガニックフードを提供するカフェ">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag ('favicon.png')%>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS -->
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/menus/edit.html.erb
<div id="contact" class="big-bg">
  <div class="wrapper">
    <h2 class="page-title">Edit the Menu</h2>
    <%= render 'layouts/menu_form' %></br>
    <%= link_to 'delete', "/menus/#{@menu.id}", method: :delete, class:"button-destroy" %>
  </div><!-- /.wrapper -->
</div><!-- /#contact -->

app/views/menus/index.html.erb
<div id="menu" class="big-bg">
  <div class="menu-content wrapper">
      <h2 class="page-title">Menu</h2>
      <% if user_signed_in? && current_user.admin? %>
        <h2 class="page-title-admin">管理画面</h2>
        <h2 class= "page-title-admin"><%= link_to "新メニュー登録", new_menu_path %></h2>
      <% else %>
        <p>
            体に優しい自然食を提供する、WEB CAFE。無添加の食材を利用したメニューがfabulousです。
            おいしいブレンドコーヒーとヘルシーなオーガニックフードで体の内側から癒やされてください。
        </p>
      <% end %>

  </div><!-- /.menu-content -->
</div><!-- /#menu -->

<% if user_signed_in? && current_user.admin? %>
<div class="wrapper grid">
  <% @menus.each do |s| %>
    <div class="item">
        <%= image_tag s.image if s.image.attached? %>
        <p><%= s.name %></p>
        <p><%= s.comment %></p>
        <%= link_to '編集する', edit_menu_path(s.id) %>
    </div>
  <% end %>
</div><!-- /.grid -->
<% else %>
<div class="wrapper grid">
  <% @menus.order(:updated_at).last(6).each do |s| %>
    <div class="item">
        <%= image_tag s.image if s.image.attached? %>
        <p><%= s.name %></p>
        <p><%= s.comment %></p>
    </div>
  <% end %>
</div><!-- /.grid -->
<% end %>

app/views/menus/new.html.erb
<div id="contact" class="big-bg">
  <div class="wrapper">
    <h2 class="page-title">Entry new Menu</h2>
        <%= form_with(model: @menu, local: true) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
          <%= f.label :comment %>
          <%= f.text_area :comment, class: 'form-control' %><BR>
          <%= f.label :photo %>
          <%= f.file_field :image %><BR>
          <%= f.submit "Create new menu", class: "button-create" %>
        <% end %>
    </div>
  </div><!-- /.wrapper -->
</div><!-- /#contact -->

app/views/menus/show.html.erb
<div class="wrapper">
  <h1>各メニューの内容確認ページです</h1>
  <h3>id: <%= @menu.id %></h3>
  <h3><%= @menu.name %></h3>
  <h3><%= @menu.comment %></h3>
  <%= image_tag @menu.image %>
  <p><%= link_to '編集する', edit_menu_path(@menu)  %></p>
</div>

app/views/static_pages/contact.html.erb
<div id="contact" class="big-bg">
  <div class="wrapper">
    <h2 class="page-title">Contact</h2>
    <form action="#">
        <div>
            <label for="name">お名前</label>
            <input type="text" id="name" name="your-name">
        </div>

        <div>
            <label for="email">メールアドレス</label>
            <input type="email" id="email" name="your-email">
        </div>

        <div>
            <label for="message">メッセージ</label>
            <textarea id="message" name="your-message"></textarea>
        </div>

        <input type="submit" class="button" value="送信">
    </form>
  </div><!-- /.wrapper -->
</div><!-- /#contact -->

<section id="location">
    <div class="wrapper">
        <div class="location-info">
            <h3 class="sub-title">カフェ 東駅前店</h3>
            <p>
                住所： 東京都〇〇区<br>
                〇〇〇〇〇〇〇 000-22-1<br>
                〇〇〇〇<br>
                電話： 03-1111-1111<br>
                営業時間： 10:00〜20:00<br>
                休日：水曜
            </p>
        </div><!-- /.location-info -->
        <div class="location-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.4466958110115!2d139.73464221478676!3d35.66600153841542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b835942e165%3A0xb4897f1f4264c771!2z44CSMTA2LTAwMzIg5p2x5Lqs6YO95riv5Yy65YWt5pys5pyo77yS5LiB55uu77yU4oiS77yV!5e0!3m2!1sja!2sjp!4v1543466837094" width="800" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div><!-- /.location-map -->
    </div><!-- /.wrapper -->
</section><!-- /#location -->

<section id="sns">
    <div class="wrapper">
        <div class="sns-box">
            <h3 class="sub-title">Facebook</h3>
            <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fwebcreatorbox.fb%2F&tabs=timeline&width=340&height=315&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false&appId=229812980409867" width="340" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
        </div>

        <div class="sns-box">
            <h3 class="sub-title">Twitter</h3>
            <a class="twitter-timeline" data-height="315" href="https://twitter.com/webcreatorbox?ref_src=twsrc%5Etfw">Tweets by webcreatorbox</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <div class="sns-box">
            <h3 class="sub-title">Youtube</h3>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/bqJtUojA1-g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div><!-- /.wrapper -->
</section><!-- /#sns -->

app/views/static_pages/home.html.erb
<div id="home" class="big-bg">
  <div class="home-content wrapper">
      <h2 class="page-title">We'll Make Your Day</h2>
      <p>おしゃれなカフェで癒やされてみませんか？無添加の食材で体の中からリフレッシュ。</p>
      <%= link_to 'メニューを見る', '/menus', {class: "button"} %>
  </div><!-- /.home-content -->
</div><!-- /#home -->

app/views/static_pages/show.html.erb
<div id="news" class="big-bg">
  <div class="wrapper">
    <h2 class="page-title">News</h2>
  </div><!-- /.wrapper -->
</div><!-- /#news -->

<% if user_signed_in? && current_user.admin?%>
<h3><%= link_to '新規作成する', '/entries/new' %></h3>
<h3><%= link_to 'News一覧をみる', '/entries' %></h3>

<% else %>

<div class="new-contents wrapper">
  <article>
    <% @entries.order(:updated_at).last(1).each do |e| %>
      <header class="post-info">
          <h2 class="post-title"><%= e.title %></h2>
          <p class="post-date"><%= e.updated_at.month %>/<%= e.updated_at.day %> <span><%= e.updated_at.year %></span></p>
          <p class="post-cat">カテゴリー：<%= e.category %></p>
          <img> <%= image_tag e.image %> </img>
          <p><%= e.content %></p>
          <p>体に優しい自然食を提供する、WEB CAFE。</p>
    <% end %>
  </article>
  <aside>
      <h3 class="sub-title">カテゴリー</h3>
      <ul class="sub-menu">
          <li><a href="#">お店の紹介</a></li>
          <li><a href="#">期間限定メニュー</a></li>
          <li><a href="#">イベント</a></li>
          <li><a href="#">お客様との会話</a></li>
      </ul>

      <h3 class="sub-title">このお店について</h3>
      <p>
          体に優しい自然食を提供する、WCB CAFE。無添加の食材を利用したメニューが特徴です。
          おいしいブレンドコーヒーとヘルシーなオーガニックフードで体の内側から癒やされてください。
      </p>
  </aside>
</div><!-- /.news-contents -->

<% end %>